### ISSUE TITLE
I intend to remove yg-randomizer

### ISSUE THREAD

**Issue by AlexCato** [JoinMarket-Org/custom-scripts#7]
Reasoning:
Imho yg-randomizer is not be needed any more and can be deleted. The yg-privacyenhanced, which comes with JM by default, basically does the same thing. yg-randomizer was introduced for the old JM, before privacyenhanced existed. There's no need to maintain both versions.

Any objections?

**Comment by takinbo** [comment]
I have no objections. I'll update #6 to have that removed.

**Comment by AlexCato** [comment]
Done by #6
